# Config file for automatic testing at travis-ci.org

language: python

python:
    - 2.7

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - export PYTHONPATH=$PWD/dioptas:$PYTHONPATH

    #start x-server
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

addons:
  apt:
    packages:
      - gfortran

install:
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy pillow scipy pandas matplotlib dateutil nose h5py pyqt scikit-image cython
    - pip install lmfit pyqtgraph fabio mock pymatgen pytest pytest-cov
    - git clone https://github.com/kif/pyFAI
    - cd pyFAI
    - python setup.py install
    - cd ..
    - cd dioptas/model/util/
    - f2py -c -m smooth_bruckner smooth_bruckner.f95
    - cd ../../../

script:
    - cd dioptas/tests
    - py.test controller_tests
    - py.test unit_tests
