# Config file for automatic testing at travis-ci.org

language: python

sudo: required

python:
    - 2.7
    - 3.6
    
cache:
  directories:
    - /home/travis/miniconda2
    - /home/travis/miniconda3

before_install:
  - echo $TRAVIS_PYTHON_VERSION
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
      if [ ! -d "/home/travis/miniconda2/bin" ]; then
        rm -rf /home/travis/miniconda2;
        wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
      fi
    fi

  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
      if [ ! -d "/home/travis/miniconda3/bin" ]; then
        rm -rf /home/travis/miniconda3;
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
      fi
    fi

  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
      export PATH=/home/travis/miniconda2/bin:$PATH;
    else
      export PATH=/home/travis/miniconda3/bin:$PATH;
    fi

  - conda update --yes conda
  - export PYTHONPATH=$PWD/dioptas:$PYTHONPATH

  #start x-server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    packages:
      - gfortran
      - libgfortran3

install:
    - conda install --yes numpy pillow scipy pandas matplotlib python-dateutil nose h5py pyqt scikit-image cython future qtpy fabio pyfai lmfit mock pytest pytest-cov -c conda-forge
    - conda install --yes pyqtgraph -c cprescher
    - pip install pyepics
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
        pip install pycifrw;
      else
        conda install pycifrw -c cprescher;
      fi
    - cd dioptas/model/util/
    - f2py -c -m smooth_bruckner smooth_bruckner.f95
    - cd ../../../

script:
    - py.test dioptas/tests/unit_tests
    - py.test dioptas/tests/controller_tests
    - py.test dioptas/tests/functional_tests
