# This is a basic workflow to help you get started with Actions

name: CD_WINDOWS

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      folder_name: 'DioptasWin'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Use Python Dependency Cache
      id: pip-cache
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('Dioptas.spec') }}-v3
        restore-keys: |
          ${{ runner.os }}-pip-c3

    - name: Install Pip Dependencies
      run: |
        pip install pycifrw pandas numpy python-dateutil h5py cython scikit-image==0.19.3 pyqt6 future qtpy pyfai lmfit pyepics extra_data pyinstaller watchdog pyopengl pyopengl-accelerate h5py hdf5plugin pyqtgraph sharedmem poetry poetry-dynamic-versioning
      # we have to use scikit-image==0.19.3 because of a new loading mechanism in 0.20.0 which does currently not work
      # with pyinstaller

    - name: Compile Smooth Bruckner
      run: cythonize -a -i dioptas\model\util\smooth_bruckner_cython.pyx

    - name: Update the Version
      run: poetry dynamic-versioning

    - name: Run Dioptas from source to test
      run: python run.py test

    - name: Run PyInstaller
      shell: cmd
      run: pyinstaller Dioptas.spec

    - name: Run Dioptas Executable
      shell: cmd
      run: |
        cd dist\Dioptas*
        Dioptas.exe test

    - name: Determine Folder Name
      run: |
        cd dist\Dioptas*
        echo "folder_name=$(pwd | Select-Object | %{$_.ProviderPath.Split("\")[-1]})"
        echo "folder_name=$(pwd | Select-Object | %{$_.ProviderPath.Split("\")[-1]})" >> $GITHUB_ENV

    - name: Upload Compressed App as Artifact to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.folder_name }}
        path: dist\Dioptas*

#     DROPBOX UPLOAD
#     disabled for now, since we can use the GitHub artifacts
#    - name: Compress App
#      run: |
#        cd dist\Dioptas*
#        $folderName = pwd | Select-Object | %{$_.ProviderPath.Split("\")[-1]}
#        cd ..
#        $zipName = $folderName + '.zip'
#        Compress-Archive $folderName $zipName
#        Write-Host((Get-Item $zipName).length/1MB)
#
#    - name: Upload Compressed App to Dropbox
#      env:
#        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
#      run: |
#        pip install dropbox
#        cd dist
#        $zipFile = Resolve-Path ".\Dioptas*.zip" | Select-Object | %{$_.ProviderPath.Split("\")[-1]}
#        $targetFile = '/develop/windows/' + $zipFile
#        python ..\scripts\dropbox_upload.py $zipFile $targetFile
