# This is a basic workflow to help you get started with Actions

name: CD_LINUX

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow

    - name: Use Miniconda
      uses: s-weigand/setup-conda@v1

    - name: switch to python=3.10 and install pip
      run: conda install python=3.10 pip -y

    - name: Install Apt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-opengl libgl1-mesa-dev libglib2.0-0

    - name: Install Pip Dependencies
      run: |
        pip install pycifrw pandas python-dateutil h5py scikit-image==0.19.3 pyqt6 cython future qtpy pyfai lmfit \
                    pyepics extra_data pyinstaller pyopengl pyopengl-accelerate watchdog h5py hdf5plugin pyqtgraph \
                    mock pytest pytest-xvfb pytest-qt setuptools_scm

    - name: Compile Smooth Bruckner
      run: cythonize -a -i dioptas/model/util/smooth_bruckner_cython.pyx

    - name: Create a Version File
      run: python -m setuptools_scm

    - name: Run Dioptas from source to test
      run: xvfb-run -e /dev/stdout python run.py test
        
    - name: Run PyInstaller
      run: bash create_executable.sh

    - name: Run Dioptas
      run: |
        cd dist/Dioptas*
        xvfb-run -e /dev/stdout ./Dioptas test

    - name: Compress Executable
      run: |
        cd dist
        export DIOPTAS_FOLDER=$(ls | grep Dioptas)
        tar -zcvf $DIOPTAS_FOLDER.tar.gz $DIOPTAS_FOLDER
        du -sh $DIOPTAS_FOLDER.tar.gz

    - name: Upload Compressed App to Dropbox
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        pip install dropbox
        cd dist
        export compressedFile=$(ls | grep .tar.gz)
        export targetFile='/develop/linux/'$compressedFile
        python ../scripts/dropbox_upload.py $compressedFile $targetFile
