# This is a basic workflow to help you get started with Actions

name: CI_batch

on: [push, pull_request]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Use Python Dependency Cache
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('Dioptas.spec') }}-c3
        restore-keys: |
          ${{ runner.os }}-pip-c3

    - name: Install Apt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-opengl libgl1-mesa-dev libglib2.0-0

    - name: Install Pip Dependencies
      run: |
        pip install pycifrw pandas python-dateutil h5py scikit-image pyqt5 cython future qtpy pyfai lmfit \
                    pyepics extra_data pyinstaller watchdog pyopengl pyopengl-accelerate h5py hdf5plugin pyqtgraph \
                    mock pytest pytest-xvfb pytest-qt

    - name: Run tests
      shell: bash -l {0}
      run: |
        py.test dioptas/tests/controller_tests/test_BatchController_part1.py
        py.test dioptas/tests/controller_tests/test_BatchController_part2.py
        py.test dioptas/tests/controller_tests/test_BatchController_part3.py
        py.test dioptas/tests/controller_tests/test_BatchController_part4.py
