# This is a basic workflow to help you get started with Actions

name: CI_backend_windows

on: [push, pull_request]

jobs:
  backend-tests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Use Python Dependency Cache
      id: pip-cache
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('Dioptas.spec') }}-v3
        restore-keys: |
          ${{ runner.os }}-pip-c3

    - name: Install Pip Dependencies
      run: |
        pip install pycifrw pandas numpy python-dateutil h5py cython scikit-image pyqt6 future qtpy pyfai lmfit pyepics extra_data pyinstaller watchdog pyopengl pyopengl-accelerate h5py hdf5plugin pyqtgraph sharedmem
        pip install pytest setuptools_scm mock
  

    - name: Run tests
      run: |
        py.test dioptas/tests/unit_tests