# This is a basic workflow to help you get started with Actions

name: CI_backend

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install poetry
      run: pip install poetry

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'

    - name: Install Apt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-opengl libgl1-mesa-dev libglib2.0-0

    - name: Install poetry dependencies
      run: poetry install

    - name: Run tests
      run: |
        poetry run py.test dioptas/tests/unit_tests/test_AutoLevel.py
        poetry run py.test dioptas/tests/unit_tests/test_background_extraction.py
        poetry run py.test dioptas/tests/unit_tests/test_BatchModel.py
        poetry run py.test dioptas/tests/unit_tests/test_calc.py
        poetry run py.test dioptas/tests/unit_tests/test_CalibrationModel.py
        poetry run py.test dioptas/tests/unit_tests/test_cif.py
        poetry run py.test dioptas/tests/unit_tests/test_DioptasModel.py
        poetry run py.test dioptas/tests/unit_tests/test_FileNameIterator.py
        poetry run py.test dioptas/tests/unit_tests/test_HelperModule.py
        poetry run py.test dioptas/tests/unit_tests/test_ImgCorrections.py
        poetry run py.test dioptas/tests/unit_tests/test_ImgModel.py
        poetry run py.test dioptas/tests/unit_tests/test_Jcpds.py
        poetry run py.test dioptas/tests/unit_tests/test_MaskModel.py
        poetry run py.test dioptas/tests/unit_tests/test_NewFileInDirectoryWatcher.py
        poetry run py.test dioptas/tests/unit_tests/test_OverlayModel.py
        poetry run py.test dioptas/tests/unit_tests/test_Pattern.py
        poetry run py.test dioptas/tests/unit_tests/test_PatternModel.py
        poetry run py.test dioptas/tests/unit_tests/test_PhaseModel.py
        poetry run py.test dioptas/tests/unit_tests/test_Signal.py
