# This is a basic workflow to help you get started with Actions

name: CI_batch

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install poetry
      run: pip install poetry

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'

    - name: Install Apt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-opengl libgl1-mesa-dev libglib2.0-0 libxkbcommon-x11-dev libxcb-xinerama0  \
          libxcb-keysyms1-dev libxcb-image0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev \
          libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-cursor0 libopengl0

    - name: Install poetry dependencies
      run: poetry install

    - name: Run tests
      run: |
        poetry run py.test dioptas/tests/controller_tests/test_BatchController_part1.py
        poetry run py.test dioptas/tests/controller_tests/test_BatchController_part2.py
        poetry run py.test dioptas/tests/controller_tests/test_BatchController_part3.py
        poetry run py.test dioptas/tests/controller_tests/test_BatchController_part4.py
