# This is a basic workflow to help you get started with Actions

name: CI_frontend

on: [push, pull_request]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Setup Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Use Python Dependency Cache
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('Dioptas.spec') }}-c3
        restore-keys: |
          ${{ runner.os }}-pip-c3

    - name: Install Apt Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libegl1-mesa libgl1-mesa-glx xserver-xorg-video-dummy libxkbcommon-x11-0 libxkbcommon0 \
          libxkbcommon-dev libxcb-icccm4 libxcb-image0 libxcb-shm0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
          libxcb-render0 libxcb-shape0 libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxcb-cursor0 libxcb1 libopengl0

    - name: Install Pip Dependencies
      run: |
        pip install pycifrw pandas python-dateutil h5py scikit-image pyqt6 cython future qtpy pyfai lmfit \
                    pyepics extra_data pyinstaller watchdog pyopengl pyopengl-accelerate h5py hdf5plugin pyqtgraph \
                    mock pytest pytest-xvfb pytest-qt

    - name: Start X server
      if: runner.os == 'Linux'
      run: |
        export DISPLAY=:99.0
        Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./99.log -config ./.github/workflows/xorg.conf :99 &
        sleep 3

    - name: Run tests
      run: |
        py.test dioptas/tests/controller_tests/test_BackgroundController.py
        py.test dioptas/tests/controller_tests/test_CalibrationController.py
        py.test dioptas/tests/controller_tests/test_ConfigurationController.py
        py.test dioptas/tests/controller_tests/test_CorrectionController.py
        py.test dioptas/tests/controller_tests/test_EpicsController.py
        py.test dioptas/tests/controller_tests/test_ImageController.py
        py.test dioptas/tests/controller_tests/test_IntegrationBackgroundController.py
        py.test dioptas/tests/controller_tests/test_IntegrationController.py
        py.test dioptas/tests/controller_tests/test_JcpdsEditorController.py
        py.test dioptas/tests/controller_tests/test_MaskController.py
        py.test dioptas/tests/controller_tests/test_OptionsController.py
        py.test dioptas/tests/controller_tests/test_OverlayController.py
        py.test dioptas/tests/controller_tests/test_PatternController.py
        py.test dioptas/tests/controller_tests/test_PhaseController.py
        py.test dioptas/tests/controller_tests/test_PhaseInCakeController.py
        py.test dioptas/tests/controller_tests/test_PhaseInPatternController.py
