# This is a basic workflow to help you get started with Actions

name: CI_functional

on: [push, pull_request]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install poetry
      run: pip install poetry

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'

    - name: Install QT Dependencies
      run: |
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

    - name: Install poetry dependencies
      run: poetry install

    - name: Run tests
      run: |
        poetry run py.test dioptas/tests/functional_tests/test_functional_JcpdsEditor.py
        poetry run py.test dioptas/tests/functional_tests/test_img_plots.py
        poetry run py.test dioptas/tests/functional_tests/test_functional_integration.py
