# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
        channels: cprescher

    - name: Install Conda Dependencies
      shell: bash -l {0}
      run: |
        conda install --yes pycifrw pandas python-dateutil h5py scikit-image future qtpy pyfai lmfit mock pytest pytest-cov pyqtgraph cython watchdog
        
    - name: Install Pip Dependencies
      shell: bash -l {0}
      run:
        pip install pyepics extra_data

    - name: Run tests
      shell: bash -l {0}
      run: |
        xvfb-run -a py.test dioptas/tests/unit_tests

        xvfb-run -a py.test dioptas/tests/controller_tests/test_BackgroundController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_CalibrationController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_ConfigurationController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_CorrectionController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_EpicsController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_ImageController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_IntegrationBackgroundController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_IntegrationController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_JcpdsEditorController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_MaskController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_OptionsController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_OverlayController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_PatternController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_PhaseController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_PhaseInCakeController.py
        xvfb-run -a py.test dioptas/tests/controller_tests/test_PhaseInPatternController.py

        xvfb-run -a py.test dioptas/tests/functional_tests
